//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace Count_Down
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<genTiming> genTimings
        {
            get
            {
                if ((_genTimings == null))
                {
                    _genTimings = base.CreateObjectSet<genTiming>("genTimings");
                }
                return _genTimings;
            }
        }
        private ObjectSet<genTiming> _genTimings;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the genTimings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogenTimings(genTiming genTiming)
        {
            base.AddObject("genTimings", genTiming);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="genTimingModel", Name="genTiming")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class genTiming : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new genTiming object.
        /// </summary>
        /// <param name="tID">Initial value of the TID property.</param>
        /// <param name="tDate">Initial value of the TDate property.</param>
        /// <param name="tDay">Initial value of the TDay property.</param>
        /// <param name="tHour">Initial value of the THour property.</param>
        /// <param name="tSequence">Initial value of the TSequence property.</param>
        /// <param name="tDuration">Initial value of the TDuration property.</param>
        public static genTiming CreategenTiming(global::System.Int32 tID, global::System.DateTime tDate, global::System.String tDay, global::System.Int32 tHour, global::System.Int32 tSequence, global::System.Int32 tDuration)
        {
            genTiming genTiming = new genTiming();
            genTiming.TID = tID;
            genTiming.TDate = tDate;
            genTiming.TDay = tDay;
            genTiming.THour = tHour;
            genTiming.TSequence = tSequence;
            genTiming.TDuration = tDuration;
            return genTiming;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TID
        {
            get
            {
                return _TID;
            }
            set
            {
                if (_TID != value)
                {
                    OnTIDChanging(value);
                    ReportPropertyChanging("TID");
                    _TID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TID");
                    OnTIDChanged();
                }
            }
        }
        private global::System.Int32 _TID;
        partial void OnTIDChanging(global::System.Int32 value);
        partial void OnTIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime TDate
        {
            get
            {
                return _TDate;
            }
            set
            {
                OnTDateChanging(value);
                ReportPropertyChanging("TDate");
                _TDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TDate");
                OnTDateChanged();
            }
        }
        private global::System.DateTime _TDate;
        partial void OnTDateChanging(global::System.DateTime value);
        partial void OnTDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TDay
        {
            get
            {
                return _TDay;
            }
            set
            {
                OnTDayChanging(value);
                ReportPropertyChanging("TDay");
                _TDay = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TDay");
                OnTDayChanged();
            }
        }
        private global::System.String _TDay;
        partial void OnTDayChanging(global::System.String value);
        partial void OnTDayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 THour
        {
            get
            {
                return _THour;
            }
            set
            {
                OnTHourChanging(value);
                ReportPropertyChanging("THour");
                _THour = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("THour");
                OnTHourChanged();
            }
        }
        private global::System.Int32 _THour;
        partial void OnTHourChanging(global::System.Int32 value);
        partial void OnTHourChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TSequence
        {
            get
            {
                return _TSequence;
            }
            set
            {
                OnTSequenceChanging(value);
                ReportPropertyChanging("TSequence");
                _TSequence = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TSequence");
                OnTSequenceChanged();
            }
        }
        private global::System.Int32 _TSequence;
        partial void OnTSequenceChanging(global::System.Int32 value);
        partial void OnTSequenceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TDuration
        {
            get
            {
                return _TDuration;
            }
            set
            {
                OnTDurationChanging(value);
                ReportPropertyChanging("TDuration");
                _TDuration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TDuration");
                OnTDurationChanged();
            }
        }
        private global::System.Int32 _TDuration;
        partial void OnTDurationChanging(global::System.Int32 value);
        partial void OnTDurationChanged();

        #endregion
    
    }

    #endregion
    
}
